language: android

android:
  components:
    - build-tools-23.0.1
    - android-23

jdk:
  - oraclejdk7
  - oraclejdk8

before_script:
  - pushd ~
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod +x android-ndk-r10e-linux-x86_64.bin
  - ./android-ndk-r10e-linux-x86_64.bin 1> /dev/null
  - export ANDROID_NDK_HOME="$HOME/android-ndk-r10e"
  - popd

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "TODO"
    - secure: "TODO"

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
